### ISSUE TITLE
Cannot load android system

### ISSUE THREAD

**Issue by CarlosCMD** [naz664/SparkOS_gsi#15]
After flashing the image, an error is displayed: "Cannot load Android system. Your data may be corrupt.... REASON IS: enablefilecrypto_failed" factory reset is not working and it's the same case with crDroid and arrow OS. Help?
![IMG20231110131557 (2)](https://github.com/naz664/SparkOS_gsi/assets/67831930/f8622753-1e36-4969-a67f-a382f90b24f2)

**Comment by kelexine** [comment]
Restore factory reset

**Comment by CarlosCMD** [comment]
I did, might have something to do with flashing using the stock recovery
(fastbootd)

**Comment by kelexine** [comment]
No, that's not it, after flashing run fastboot reboot bootloader, then fastboot -w

**Comment by CarlosCMD** [comment]
I've erased userdata a couple of times, lemme forward device info from
Treble app

**Comment by CarlosCMD** [comment]
Device Info 3.3.5.9
Date Created 2023-11-10 17:32:12

Device
--------------------------------------------------------
Device Name : trebledroid with gapps
Model : TrebleDroid with GApps
Manufacturer : unknown
Device : tdgsi_a64_ab
Board : sp9832e_1h10_32b
Hardware : sp9832e_1h10_go
Brand : google
Build Fingerprint : google/lineage_a64_bgN/tdgsi_a64_ab:13/TQ3A.230901.001/eng.crossg.20231018.003231:userdebug/test-keys


System
--------------------------------------------------------
Android Version : 13
Version Name : T
Released Date : August 15, 2022
Code Name : Android 13
API Level : 33
Security Patch Level : 2023-10-06
Bootloader : unknown
Build Number : lineage_a64_bgN-userdebug 13 TQ3A.230901.001 eng.crossg.20231018.003231 test-keys
Baseband : _W21.04.2|sc9832e_modem|01-19-2021 12:19:04
Java VM : 2.1.0
Kernel : 4.14.133+
Language : English (en_GB)
OpenGL ES : 3.2
Root Management Apps : Magisk
SELinux : Unable to determine
Google Play Services : 23.44.14 (200306-580326705)
Vulkan : Supported (1.1)
Treble : Supported
Seamless Updates : Not Supported


CPU
--------------------------------------------------------
SoC : tdgsi_a64_ab (no)
no
Processor : unknown unknown
CPU Architecture : 4 x 1.40 GHz
Supported ABIs : armeabi-v7a, armeabi
CPU Hardware : Unisoc SC9832e
CPU Type : 32 Bit
CPU Governor : interactive
Cores : 4
CPU Frequency : 4 x 768 MHz - 1400 MHz
GPU Renderer : Mali-T820
GPU Vendor : ARM
GPU Version : OpenGL ES 3.2 v1.r28p0-01rel0.f824eff111575c5ed61c9e0592018f55


Battery
--------------------------------------------------------
Health : Good
Level : 38%
Status : Discharging
Power Source : Battery
Technology : 
Temperature : 37 ℃
Voltage : 3695 mV







Connectivity
--------------------------------------------------------
Bluetooth
------------------
Bluetooth : Supported
Multiple Advertisements : Not Supported
Offloaded Filtering : Supported
Offloaded Scan Batching : Supported
Bluetooth LE (Low Energy) : Supported
LE 2M PHY (High Speed) : Not Supported
LE Coded PHY (Long Range) : Not Supported
LE Extended Advertising : Not Supported
LE Periodic Advertising : Not Supported
LE Audio : Not Supported

Wi-Fi
------------------
WiFi Standard : Wi-Fi 4
WiFi Direct : Supported
5GHz : Not Supported
6GHz : Not Supported

NFC
------------------
NFC : Not Supported
Secure NFC : Not Supported

Ultra Wide Band
------------------
Ultra Wide Band : Not Supported

USB
------------------
USB Host : Supported
USB Accessory : Supported
USB Debugging : On


Display
--------------------------------------------------------
Resolution : 1560 x 720 Pixels (HD+)
Density : 320 dpi (XHDPI)
Font Scale : 1.0
Physical Size : 6.1 inches
Refresh Rate : • 60.0 Hz
HDR : Not Supported
HDR Capabilities : None
Brightness Level : 16%
Brightness Mode : Manual
Screen Timeout : 120 Seconds
Orientation : Portrait


Memory
--------------------------------------------------------
Random Access Memory
------------------
Total : 1893.0MB
Available : 699.0MB
Used : 1208.0MB
Used Percentage : 63%

System Storage
------------------
Total : 2.15GB
Available : 0.17GB
Used : 1.97GB
Used Percentage : 91%

Internal Storage
------------------
Total : 26.04GB
Available : 19.66GB
Used : 6.38GB
Used Percentage : 24%

External Storage
------------------
Total : 3.75GB
Available : 1.89GB
Used : 1.85GB
Used Percentage : 49%


Camera
--------------------------------------------------------
Camera - 0
------------------
Position : Back
Mega Pixels : 5 MP
Resolution : 2592 x 1944
Focal Length : 2.261mm

Camera - 1
------------------
Position : Front
Mega Pixels : 5 MP
Resolution : 2592 x 1944
Focal Length : 2.696mm



Sensors
--------------------------------------------------------
SILAN SC7A20 3-axis Accelerometer
------------------
Vendor : SILAN
Type : ACCELEROMETER
Power : 0.145mA

Msg2xxx Proximity sensor
------------------
Vendor : MSTAR
Type : PROXIMITY
Power : 0.005mA

**Comment by CarlosCMD** [comment]
I've spotted the problem and it's because of the patched magisk boot image.

**Comment by kelexine** [comment]
Then you should report the bug to @topjohnwu
