### ISSUE TITLE
Is it possiable to make VNDK Lite version of Spark OS based on Android 13?

### ISSUE THREAD

**Issue by muhammadbahaa2001** [naz664/SparkOS_gsi#2]
I have a Huawei device that supports Treble Project shipped with VNDK 28.0 but only can boot VNDK Lite GSI ROMs, I hope you make VNDK Lite version of Spark OS based on Android 13 for A/B ARM64 device with/without Google Apps.

**Comment by naz664** [comment]
Well you can make it manually,
Extract the normal build and rename spark..img to system.img.
with the help of  [sas-creator](https://github.com/AndyCGYan/sas-creator)
you can easily convert it to vndklite build.
